[patterns.glider]
coords = [
  [1, 0],
  [2, 1],
  [0, 2],
  [1, 2],
  [2, 2],
]

[patterns.blinker]
coords = [
  [0, 1],
  [1, 1],
  [2, 1],
]

[patterns.block]
coords = [
  [0, 0],
  [1, 0],
  [0, 1],
  [1, 1],
]
