general {
    lock_cmd = {{HOME}}/.local/bin/lifesuspendctl lock
    before_sleep_cmd = loginctl lock-session
}

listener {
    timeout = 10
    on-timeout = {{HOME}}/.local/bin/lifesuspendctl show
    on-resume = {{HOME}}/.local/bin/lifesuspendctl hide
}

listener {
    timeout = 300
    on-timeout = {{HOME}}/.local/bin/lifesuspendctl lock
}
